language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install: "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'virtualenv<14.0.0'; fi"
install: "pip install -r requirements.txt"
script: pylama
